#!/usr/bin/python
# 123 === VJ0/ukhzxDHto
# 1234 === oViiZIBqDeqIM
# qwer === FaVOBJa4yOmr2

from sys import argv
import os
start_of_line = '^'

credentails = {'one': 'VJ0/ukhzxDHto','two': 'oViiZIBqDeqIM', 'three': 'FaVOBJa4yOmr2'}
# print credentials
#for name in credentials:
#    print name
for key, value in credentails.iteritems():
    #Check the out put of the linux command.
    check_userexit = 'cat /etc/passwd | grep %s+%s | cut -d: -f1' % (start_of_line,key)
    u1 = os.popen(check_userexit)
    u2 = u1.read()

    # Check user exist or not
    # Strip(remove) space from value.
    if u2.strip() == key:
        print 'The user %s already exist' % key
    else:
        flag = raw_input('The user %s does not exit. Do you want to create (y/n)')
        if flag.strip() == 'y':
        # The value RoYn8vC3ZdTWo generated by command  'openssl passwd -crypt <userpassword>'.
        # If user not exist then following command will create the user with their encrypted password.
           os.system('sudo  useradd -m -d /home/%s -s /bin/bash -p %r %s' %(key,value,key))
           print 'The user %s created successfully' % key
