#!/usr/bin/python
# Add the user to system with encrypted password.
# Author: Swapnil V Zarbade

from sys import argv
import os

# from user input
script, username = argv

# The value present at  start of the line.
start_of_line = '^'
name = start_of_line + username

#Check the out put of the linux command.
check_userexit = 'cat /etc/passwd | grep %s | cut -d: -f1' % name
u1 = os.popen(check_userexit)
u2 = u1.read()

# Check user exist or not
# Strip(remove) space from value.
if u2.strip() == username:
   print 'The user %s already exist' % username
else:
   flag = raw_input('The user %s does not exit. Do you want to create (y/n)')
   if flag.strip() == 'y':
      # The value RoYn8vC3ZdTWo generated by command  'openssl passwd -crypt <userpassword>'.
      # If user not exist then following command will create the user with their encrypted password.
      os.system('sudo  useradd -m -d /home/%s -s /bin/bash -p RoYn8vC3ZdTWo %s' %(username,username))
      print 'The user %s created successfully' % username
